// This file is auto-generated by @signlab/vue-route-gen.
// Do not edit this file directly.
import type { RouteRecordRaw, RouteLocationNormalizedLoaded, Router, LocationQuery } from 'vue-router';

export const ROUTE_NAME = {
  ABOUT: "about",
  INDEX: "index",
  USERS_ID: "users-[id]",
  USERS_INDEX: "users-index",
} as const;

export type RouteName = (typeof ROUTE_NAME)[keyof typeof ROUTE_NAME];

export const ROUTE_PATH = {
  ABOUT: "/about",
  INDEX: "/",
  USERS_ID: "/users/:id",
  USERS_INDEX: "/users",
} as const;

export type RoutePath = (typeof ROUTE_PATH)[keyof typeof ROUTE_PATH];

export const ROUTE_PATH_BY_NAME = {
  "about": ROUTE_PATH.ABOUT,
  "index": ROUTE_PATH.INDEX,
  "users-[id]": ROUTE_PATH.USERS_ID,
  "users-index": ROUTE_PATH.USERS_INDEX,
} as const;

export type RoutePathByName = typeof ROUTE_PATH_BY_NAME;

export const routeNameList = [
  "about",
  "index",
  "users-[id]",
  "users-index",
] as const;

export const routePathList = [
  "/about",
  "/",
  "/users/:id",
  "/users",
] as const;

export const routePathByName = {
  "about": "/about",
  "index": "/",
  "users-[id]": "/users/:id",
  "users-index": "/users",
} as const;

// Route parameter types
export interface RouteParams {
  'about': Record<string, never>;
  'index': Record<string, never>;
  'users-[id]': {
    id: string;
  };
  'users-index': Record<string, never>;
}

export type RouteParamsByName<T extends RouteName> = RouteParams[T];

export const routes = [
  {
    path: "/about",
    name: "about",
    component: () => import("../pages/about.vue"),
    meta: {"title":"About Us","layout":"default","keepAlive":false,"requiresAuth":false},
    children: [],
  },
  {
    path: "/",
    name: "index",
    component: () => import("../pages/index.vue"),
    meta: {"title":"Home","layout":"default","keepAlive":true,"requiresAuth":false},
    children: [],
  },
  {
    path: "/users/:id",
    name: "users-[id]",
    component: () => import("../pages/users/[id].vue"),
    meta: {"title":"User Detail","layout":"admin","requiresAuth":true,"roles":["admin","moderator"]},
    children: [],
  },
  {
    path: "/users",
    name: "users-index",
    component: () => import("../pages/users/index.vue"),
    meta: {"title":"Users List","layout":"admin","requiresAuth":true,"roles":["admin"]},
    children: [],
  }
] satisfies RouteRecordRaw[];

export default routes;

// Type-enhanced hooks
import { useRoute as vueUseRoute, useRouter as vueUseRouter } from 'vue-router';

/**
 * Type-safe useRoute hook
 * Route params are typed based on the current route name
 *
 * @example
 * ```ts
 * const route = useRoute();
 * // route.params.id is typed as string if route has :id param
 * ```
 */
export function useRoute<TName extends RouteName = RouteName>(
  name?: TName
): Omit<RouteLocationNormalizedLoaded, 'params' | 'name'> & {
  name: TName;
  params: TName extends keyof RouteParams ? RouteParams[TName] : RouteParams[RouteName];
} {
  return vueUseRoute() as any;
}

/**
 * Type-safe useRouter hook
 * Navigation methods are type-safe based on route names and params
 *
 * @example
 * ```ts
 * const router = useRouter();
 * router.push({
 *   name: ROUTE_NAME.USER_DETAIL,
 *   params: { id: '123' }
 * });
 * ```
 */
export function useRouter(): Omit<Router, 'push' | 'replace'> & {
  push: <TName extends RouteName>(location: {
    name?: TName;
    path?: string;
    params?: TName extends keyof RouteParams ? Partial<RouteParams[TName]> : Record<string, any>;
    query?: LocationQuery;
    hash?: string;
  }) => ReturnType<Router['push']>;
  replace: <TName extends RouteName>(location: {
    name?: TName;
    path?: string;
    params?: TName extends keyof RouteParams ? Partial<RouteParams[TName]> : Record<string, any>;
    query?: LocationQuery;
    hash?: string;
  }) => ReturnType<Router['replace']>;
} {
  const router = vueUseRouter();
  return router as any;
}

